#!/usr/bin/env python3
"""Convert .config (kconfiglib output) to scbb_config.h"""

import sys
from pathlib import Path

def parse_config(config_path):
    result = {}
    with open(config_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                result[key.strip()] = val.strip()
    return result

def generate_header(config, output_path):
    lines = [
        "/*",
        " * Auto-generated by menuconfig.py — do not edit manually.",
        " * Run 'python menuconfig.py' to reconfigure.",
        " */",
        "",
        "#ifndef SCBB_CONFIG_H",
        "#define SCBB_CONFIG_H",
        "",
    ]

    # Module enables
    module_keys = [
        "SCBB_CH224A_ENABLED",
        "SCBB_SHT3X_ENABLED",
        "SCBB_WS2812_ENABLED",
        "SCBB_HXD039B2_ENABLED",
    ]
    lines.append("/* Module enables */")
    for key in module_keys:
        if config.get(key) == "y":
            lines.append(f"#define {key} 1")
    lines.append("")

    # BSP headers
    bsp_keys = [
        "SCBB_BSP_I2C_HEADER",
        "SCBB_BSP_GPIO_HEADER",
        "SCBB_BSP_DELAY_HEADER",
        "SCBB_BSP_UART_HEADER",
        "SCBB_BSP_PWM_DMA_HEADER",
    ]
    lines.append("/* BSP headers */")
    for key in bsp_keys:
        val = config.get(key, "")
        if val and val != '""':
            lines.append(f'#define {key} {val}')
    lines.append("")

    lines.append("#endif /* SCBB_CONFIG_H */")
    lines.append("")

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")

def main():
    config_path = sys.argv[1] if len(sys.argv) > 1 else ".config"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "scbb_config.h"

    if not Path(config_path).exists():
        print(f"Error: {config_path} not found. Run 'python menuconfig.py' first.", file=sys.stderr)
        sys.exit(1)

    config = parse_config(config_path)
    generate_header(config, output_path)
    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
